version: '3.7'

services:
 spark-master:
  image: bitnami/spark:latest
  command: bin/spark-class org.apache.spark.deploy.master.Master
  ports:
    - "9090:8080"
    - "7077:7077"
  volumes: 
    - C:/Users/alanl/pinnacle/big_data_lambda_stream/analytics_results:/opt/spark/app-result
    - C:/Users/alanl/pinnacle/big_data_lambda_stream/finnhub-data:/opt/spark/app-data
    - C:/Users/alanl/pinnacle/big_data_lambda_stream/spark-app:/opt/spark/spark-app
    - spark-logs:/opt/spark/spark-events
 spark-worker-1:
  image: bitnami/spark:latest
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: worker
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 2g
    SPARK_MASTER_URL: spark://spark-master:7077
  volumes:
    - C:/Users/alanl/pinnacle/big_data_lambda_stream/analytics_results:/opt/spark/app-result
    - C:/Users/alanl/pinnacle/big_data_lambda_stream/finnhub-data:/opt/spark/app-data
    - C:/Users/alanl/pinnacle/big_data_lambda_stream/spark-app:/opt/spark/spark-app
    - spark-logs:/opt/spark/spark-events
 spark-worker-2:
  image: bitnami/spark:latest
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: worker
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 2g
    SPARK_MASTER_URL: spark://spark-master:7077
  volumes:
    - C:/Users/alanl/pinnacle/big_data_lambda_stream/analytics_results:/opt/spark/app-result
    - C:/Users/alanl/pinnacle/big_data_lambda_stream/finnhub-data:/opt/spark/app-data
    - C:/Users/alanl/pinnacle/big_data_lambda_stream/spark-app:/opt/spark/spark-app
    - spark-logs:/opt/spark/spark-events

volumes:
  spark-logs: