FROM apache/airflow:2.8.0-python3.11

USER root
RUN apt update \
  && apt install -y openjdk-17-jdk

ENV JAVA_HOME=/usr \
    SPARK_HOME=/home/airflow/.local/lib/python3.11/site-packages/pyspark

USER airflow

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt